export ARCHFLAGS="-arch x86_64"
export EDITOR='vim'
export PATH="$HOME/bulk/.screenlayout:$PATH"
export PATH="$HOME/dotfiles/scripts:$PATH"
export PATH="$HOME/bulk/external/pip-pop/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/bulk/external/restic:$PATH"
export PATH="$HOME/bulk/external/Ryver:$PATH"
export BROWSER=chromium-browser
export PAGER="most"
export DJANGO_SETTINGS_MODULE=ebadu.settings
