export ARCHFLAGS="-arch x86_64"
export EDITOR='vim'
export PATH="$HOME/.screenlayout:$PATH"
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/external/pip-pop/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/external/restic:$PATH"
export BROWSER=chromium-browser
export PAGER="most"
export DJANGO_SETTINGS_MODULE=ebadu.settings
