#!/bin/bash

# compton (not sure what are the benefits from using it)
#al-compositor --start &

# set proper keyboard layout, polish
setxkbmap -model microsoft4000 -layout pl

# enable numlock (disable for laptop)
numlockx &

# restore wallpaper
nitrogen --restore &

# required for xfce settings to work
#xfsettingsd &

# fancy window switcher (rarely used, consider removal)
skippy-xd --config ~/.config/skippy-xd/skippy-xd.rc --start-daemon &

# start the panel (disabled, use W-F12 to toggle polybar)
#al-polybar-session &

# use autorandr to set monitor configuration if known detected
autorandr --change

# redshift - color temperature adjustment
redshift -c ~/.redshiftgrc &

# dropbox
dropbox &

# start drop-down terminal (Press F1 to pull down the window)
tilda &
