#!/usr/bin/env bash

# clear packages cache - keep only last version of recently installed packages
pacclear -rk 1 &

# compton (not sure what are the benefits from using it)
#al-compositor --start &

# set proper keyboard layout, polish but dot on numeric keyboard keep '.' not ','
setxkbmap -model microsoft4000 -layout pl -option kpdl:dot

# enable numlock (disable for laptop)
numlockx &

# restore wallpaper
nitrogen --restore &

# required for xfce settings to work
#xfsettingsd &

# fancy window switcher (rarely used, consider removal)
# skippy-xd --config ~/.config/skippy-xd/skippy-xd.rc --start-daemon &

# start the panel (disabled, use W-F12 to toggle polybar)
#al-polybar-session &

# use autorandr to set monitor configuration if known detected
autorandr --change

# redshift - color temperature adjustment
redshift -c ~/.redshiftgrc &

# dropbox
dropbox &

# onedrive (any option to use?)
#onedrive

# start drop-down terminal (Press F1 to pull down the window)
tilda &

# start Safe Eyes that protects your eyes from eye strain
#safeeyes & # for some reason safeeyes is not always starting
$HOME/dotfiles/scripts/safeeyes_delayed_start.sh

# start screen saver (skip splash screen at startup: -nosplash)
# xscreensaver -nosplash&

# save last boots info (journalctl store very limited number of boots)
$HOME/dotfiles/scripts/save-boot-time.sh &

# fetch my hackernews favourites and save to csv
$HOME/scripts/get_hn_favs.sh &

